### ISSUE TITLE
error with StringIO cannot read config_file

### ISSUE THREAD

**Issue by Notmarrco** [photo/openphoto-python#67]
Hi,
I'm not sure it's an issue due to trovebox or to my OS, but in auth.py it can't read my config file anymore.

I changed it to :

```
    with open(config_path, "r") as conf:
        res = conf.read()
        buf.write(unicode(res))
```

and it works now.

It seems to me it is some kind of issue with having python3 and python2.7 on the same system. With StringIO I can't use the "open" method.

**Comment by sneakypete81** [comment]
The problematic lines are:

```
try:
    import io # Python3
except ImportError:
    import StringIO as io # Python2
```

There is actually no need for this, since all supported Python versions (2.6, 2.7, 3.3) should include the io module.

I'm not sure why this is affecting you though. Which Python version have you found not to work? What happens if you open a Python console and type:

```
import io
```

Your proposed change looks ok for Python2, but won't work in Python3.

**Comment by sneakypete81** [comment]
Also, can you please post the exact error and traceback that you've been seeing?

**Comment by sneakypete81** [comment]
@Notmarrco: please reopen if you still see this problem with v0.6.1
